name: 发布测试环境

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@master
        with:
          node-version: '14'

      - run: npm install

      - run: npm run build:test

      - name: Upload dist
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.PASSWORD }}
          source: "dist"
          target: "/home/test"
          overwrite: true

      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/test
            sudo rm -r -f admin-front
            sudo mv dist -f admin-front
            sudo systemctl restart nginx