name: 发布测试环境

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@master
        with:
          node-version: '14'

      - run: npm install

      - run: npm run build

      - name: Build Docker image
        run: docker build -t ${{ secrets.APP_NAME }}:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker pull ${{ secrets.APP_NAME }}:latest
            docker stop ${{ secrets.APP_NAME }} || true
            docker rm spring-boot-app || true
            docker run -d --name ${{ secrets.APP_NAME }} -p 8080:80 ${{ secrets.APP_NAME }}:latest